Repository nos/client, pull requests merged in 2018-07, with the labels that each got.

#294 chore(balances): fix token list across networks
  src/renderer/shared/util/getBalances.js
Labels: PR: needs review

#296 Add nOSNet Custom Network
  src/renderer/root/util/updateNetworks.js
  src/renderer/settings/values/networks.js
Labels: PR: good to merge, enhancement

#289 feat(nep5transfer): ability to transfer NEP-5 tokens
  src/renderer/account/components/Account/index.js
  src/renderer/account/components/AccountPanel/index.js
  src/renderer/account/components/SendPanel/SendPanel.js
  src/renderer/account/components/SendPanel/index.js
  src/renderer/browser/actions/makeInvokeActions.js
  src/renderer/browser/actions/makeTestInvokeActions.js
  src/renderer/shared/util/createScript.js
  src/renderer/shared/util/encodeArgs.js
  src/renderer/shared/util/sendAsset.js
Labels: PR: reviewed w/ comments

#298 chore(package): add webpack-dev-server to greenkeeper ignore
  package.json
Labels: PR: needs review

#299 chore(browser): disabled styling for navigation buttons
  src/renderer/browser/components/AddressBar/AddressBar.scss
Labels: PR: needs review

#300 chore(package): updated version to 0.2.2
  package.json
Labels: PR: needs review

#311 chore(main): set nOS to fullscreen
  src/main/index.js
Labels: PR: needs review

#319 Fix(App component):Minimize, Maximize, Close buttons clicking
  src/renderer/root/components/App/App.scss
  src/renderer/root/components/App/ButtonBar/ButtonBar.scss
Labels: PR: good to merge

#314 chore(package.json): replaced concurrently with npm-run-all
  package.json
  yarn.lock
Labels: PR: good to merge

#333 chore(settings): set nOSNet as default fallback
  src/renderer/settings/actions/currentNetworkActions.js
  src/renderer/settings/components/NetworkPanel/NetworkPanel.js
  src/renderer/settings/values/networks.js
  src/renderer/shared/hocs/withLoadingProp.js
Labels: PR: good to merge

#301 feat(nav): open pages in tabs
  .babelrc
  __mocks__/fileMock.js
  __mocks__/svgMock.js
  __tests__/renderer/browser/index.test.js
  __tests__/renderer/root/components/App/Routes.test.js
  __tests__/renderer/root/components/App/Routes/index.test.js
  __tests__/renderer/root/components/Layout/AuthenticatedLayout/AuthenticatedLayout.test.js
  config/webpack.renderer.js
  package.json
  src/renderer/browser/actions/browserActions.js
  src/renderer/browser/components/AddressBar/AddressBar.js
  src/renderer/browser/components/AddressBar/index.js
  src/renderer/browser/components/Browser/Browser.js
  src/renderer/browser/components/Browser/Browser.scss
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  src/renderer/browser/components/InternalPage/InternalPage.js
  src/renderer/browser/components/InternalPage/index.js
  src/renderer/browser/components/Session/Session.js
  src/renderer/browser/components/Session/Session.scss
  src/renderer/browser/components/Session/index.js
  src/renderer/browser/reducers/browserReducer.js
  src/renderer/browser/shapes/tabShape.js
  src/renderer/browser/values/browserValues.js
  src/renderer/login/components/Login/Login.js
  src/renderer/register/components/Register/Register.js
  src/renderer/root/components/App/Routes/Routes.js
  src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.js
  src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.scss
  src/renderer/root/components/AuthenticatedLayout/AddressBar/index.js
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.js
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
  src/renderer/root/components/AuthenticatedLayout/Tab/index.js
  src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.js
  src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.scss
  src/renderer/root/components/AuthenticatedLayout/TabLink/index.js
  src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
  src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.scss
  src/renderer/root/components/AuthenticatedLayout/Tabs/index.js
  src/renderer/root/components/AuthenticatedLayout/index.js
  src/renderer/shared/components/Icon/Icon.js
  src/renderer/shared/images/icons/account.svg
  src/renderer/shared/images/icons/back.svg
  src/renderer/shared/images/icons/dapps.svg
  src/renderer/shared/images/icons/forward.svg
  src/renderer/shared/images/icons/logout.svg
  src/renderer/shared/images/icons/notifications.svg
  src/renderer/shared/images/icons/reload.svg
  src/renderer/shared/images/icons/settings.svg
  src/renderer/shared/images/icons/sidebar-active.svg
  src/renderer/shared/images/icons/sidebar.svg
  src/renderer/shared/util/getInternalPageComponent.js
  src/renderer/shared/util/isInternalPage.js
  yarn.lock
Labels: PR: good to merge

#336 chore(nav): fixed navigation check to remove unneeded argument
  src/renderer/browser/reducers/browserReducer.js
Labels: PR: good to merge

#316 chore(docs): removed docs and updated readme accordingly
  .github/PULL_REQUEST_TEMPLATE.md
  .github/screenshot.png
  README.md
  docs/README.md
  docs/api.md
  docs/create-your-own-dapp.md
  docs/logo.png
  docs/nos-local.md
  docs/screenshot.png
Labels: PR: good to merge

#354 chore(browser): prevent page errors for sub-resources
  src/renderer/browser/components/DAppContainer/DAppContainer.js
Labels: PR: needs review

#351 feat(tabs): reset on logout
  __tests__/renderer/browser/actions/browserActions.test.js
  __tests__/renderer/browser/reducers/browserReducer.test.js
  src/renderer/browser/actions/browserActions.js
  src/renderer/browser/reducers/browserReducer.js
  src/renderer/logout/components/Logout/index.js
Labels: PR: good to merge

#352 chore(wallet): responsive wallet
  src/common/stylesheets/variables.scss
  src/renderer/account/components/Account/Account.js
  src/renderer/account/components/Account/Account.scss
  src/renderer/account/components/AccountPanel/AccountPanel.scss
  src/renderer/account/components/AccountPanel/Holdings/Holdings.scss
  src/renderer/account/components/SendPanel/SendPanel.scss
  src/renderer/shared/components/Page/Page.js
  src/renderer/shared/components/Page/Page.scss
  src/renderer/shared/components/Page/index.js
  src/renderer/shared/index.js
Labels: PR: good to merge

#359 chore(button): cleanup
  src/renderer/account/components/SendPanel/SendPanel.js
  src/renderer/account/components/SendPanel/SendPanel.scss
  src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.scss
  src/renderer/register/components/RegisterForm/RegisterForm.scss
  src/renderer/shared/components/Forms/Button/Button.scss
  src/renderer/shared/components/Forms/Input/Input.scss
  src/renderer/shared/components/Forms/Select/Select.scss
Labels: PR: reviewed w/ comments

#365 chore(send): restore network for sending assets/tokens
  src/renderer/account/components/SendPanel/index.js
Labels: PR: needs review

#364 Minor rendering performance improvements
  src/renderer/account/components/AccountPanel/Breakdown/Breakdown.js
  src/renderer/account/components/AccountPanel/Holdings/Holdings.js
  src/renderer/account/components/AccountPanel/TokenBalance/TokenBalance.js
  src/renderer/account/components/SendPanel/SendPanel.js
  src/renderer/browser/components/Browser/Browser.js
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  src/renderer/browser/components/Error/Error.js
  src/renderer/browser/components/InternalPage/InternalPage.js
  src/renderer/browser/components/RequestsProcessor/ClaimGas/ClaimGas.js
  src/renderer/browser/components/RequestsProcessor/GetAddress/GetAddress.js
  src/renderer/browser/components/RequestsProcessor/GetBalance/GetBalance.js
  src/renderer/browser/components/RequestsProcessor/GetStorage/GetStorage.js
  src/renderer/browser/components/RequestsProcessor/Invoke/Invoke.js
  src/renderer/browser/components/RequestsProcessor/RequestProcessor.js
  src/renderer/browser/components/RequestsProcessor/RequestsProcessor.js
  src/renderer/browser/components/RequestsProcessor/Send/Send.js
  src/renderer/browser/components/RequestsProcessor/TestInvoke/TestInvoke.js
  src/renderer/browser/hocs/withClean.js
  src/renderer/browser/hocs/withPrompt/index.js
  src/renderer/browser/hocs/withRejectMessage.js
  src/renderer/login/components/Login/Login.js
  src/renderer/login/components/LoginFormLedger/LoginFormLedger.js
  src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.js
  src/renderer/login/components/LoginFormWIF/LoginFormWIF.js
  src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js
  src/renderer/logout/components/Logout/Logout.js
  src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.js
  src/renderer/register/components/AccountDetails/SaveAccount/SaveAccount.js
  src/renderer/register/components/Register/Register.js
  src/renderer/register/components/RegisterForm/RegisterForm.js
  src/renderer/root/components/App/ButtonBar/ButtonBar.js
  src/renderer/root/components/App/DialogPresenter/DialogPresenter.js
  src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.js
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.js
  src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.js
  src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
  src/renderer/root/components/PrivateRoute/PrivateRoute.js
  src/renderer/settings/components/GeneralSettings/GeneralSettings.js
  src/renderer/settings/components/NetworkSettings/NetworkSettings.js
  src/renderer/shared/components/Alert/Alert.js
  src/renderer/shared/components/Confirm/Confirm.js
  src/renderer/shared/components/Forms/Button/Button.js
  src/renderer/shared/components/Forms/Input/Input.js
  src/renderer/shared/components/Forms/Select/Select.js
  src/renderer/shared/components/Modal/Modal.js
  src/renderer/shared/components/Portal/Portal.js
  src/renderer/shared/components/Tabs/Tabs.js
  src/renderer/shared/hocs/withImmediateReset.js
  src/renderer/shared/hocs/withInitialCall.js
  src/renderer/shared/hocs/withProgressChange.js
Labels: PR: good to merge

#366 chore(main): refactor util functions
  .eslintrc.json
  src/main/index.js
  src/main/util/bindMenus.js
  src/main/util/injectHeaders.js
  src/main/util/installExtensions.js
Labels: PR: good to merge

#378 chore(browser): open new windows/tabs in nos client
  __tests__/renderer/browser/components/DAppContainer/DAppContainer.test.js
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  src/renderer/browser/components/DAppContainer/index.js
Labels: PR: needs review

#379 chore(browser): add tab separators
  src/renderer/account/components/AccountPanel/Breakdown/SectionLabel/SectionLabel.scss
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
Labels: PR: needs review

#381 chore(tabs)/Don't open new tab if this menu item is opened
  src/renderer/browser/reducers/browserReducer.js
Labels: PR: good to merge

#384 nOS docs link fix
  static/welcome.html
Labels: PR: good to merge

#383 feat(browser): restore webview focus when window is focused
  src/renderer/browser/components/DAppContainer/DAppContainer.js
Labels: PR: good to merge

#385 feat(account): receive tab & update tab designs
  __tests__/renderer/account/components/TransactionsPanel/Receive/Receive.test.js
  __tests__/renderer/account/components/TransactionsPanel/Receive/index.test.js
  __tests__/renderer/account/components/TransactionsPanel/index.test.js
  __tests__/renderer/account/index.test.js
  package.json
  src/renderer/account/components/Account/Account.js
  src/renderer/account/components/SendPanel/SendPanel.scss
  src/renderer/account/components/TransactionsPanel/IconTab/IconTab.js
  src/renderer/account/components/TransactionsPanel/IconTab/IconTab.scss
  src/renderer/account/components/TransactionsPanel/IconTab/index.js
  src/renderer/account/components/TransactionsPanel/Receive/Receive.js
  src/renderer/account/components/TransactionsPanel/Receive/Receive.scss
  src/renderer/account/components/TransactionsPanel/Receive/index.js
  src/renderer/account/components/TransactionsPanel/Send/Send.js
  src/renderer/account/components/TransactionsPanel/Send/Send.scss
  src/renderer/account/components/TransactionsPanel/Send/index.js
  src/renderer/account/components/TransactionsPanel/TransactionsPanel.js
  src/renderer/account/components/TransactionsPanel/TransactionsPanel.scss
  src/renderer/account/components/TransactionsPanel/index.js
  src/renderer/login/components/Login/Login.js
  src/renderer/login/components/Login/Login.scss
  src/renderer/login/components/LoginFormLedger/LoginFormLedger.scss
  src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.scss
  src/renderer/login/components/LoginFormWIF/LoginFormWIF.scss
  src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.scss
  src/renderer/register/components/AccountDetails/AccountDetails.scss
  src/renderer/register/components/Register/Register.js
  src/renderer/register/components/Register/Register.scss
  src/renderer/register/components/RegisterForm/RegisterForm.scss
  src/renderer/root/stylesheets/global.scss
  src/renderer/shared/components/Forms/Button/Button.scss
  src/renderer/shared/components/Tabs/Tabs.js
  src/renderer/shared/components/Tabs/Tabs.scss
  src/renderer/shared/images/account/receive.svg
  src/renderer/shared/images/account/send.svg
  src/renderer/shared/images/account/transactions.svg
  yarn.lock
Labels: PR: reviewed w/ comments
