Repository nos/client, pull requests merged in 2018-10, with the labels that each got.

#603 chore(menu): open help link in nOS when possible
  src/main/util/bindMenus.js
  src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
  src/renderer/root/components/AuthenticatedLayout/Tabs/index.js
  src/renderer/root/components/LoginLayout/LoginLayout.js
Labels: PR: needs review

#615 chore(menu): restore context menus
  src/main/index.js
  src/main/util/bindContextMenu.js
Labels: PR: good to merge

#623 chore(generalSettings): fixed not being able to select currency
  src/renderer/settings/components/GeneralSettings/GeneralSettings.js
  yarn.lock
Labels: PR: good to merge

#617 chore(invoke): pass fee to invocation config
  src/renderer/browser/components/RequestsProcessor/Invoke/index.js
Labels: PR: good to merge

#621 chore(browser): render error pages within webview
  __tests__/renderer/browser/actions/browserActions.test.js
  __tests__/renderer/browser/components/DAppContainer/DAppContainer.test.js
  __tests__/renderer/browser/index.test.js
  __tests__/renderer/browser/reducers/browserReducer.test.js
  __tests__/renderer/root/components/App/Routes.test.js
  __tests__/renderer/root/components/App/Routes/index.test.js
  __tests__/renderer/root/components/Layout/AuthenticatedLayout/AuthenticatedLayout.test.js
  package.json
  src/renderer/browser/actions/browserActions.js
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  src/renderer/browser/components/DAppContainer/DAppContainer.scss
  src/renderer/browser/components/DAppContainer/index.js
  src/renderer/browser/components/Error/Error.js
  src/renderer/browser/components/Error/Error.scss
  src/renderer/browser/components/Error/index.js
  src/renderer/browser/reducers/browserReducer.js
  src/renderer/browser/shapes/tabShape.js
  static/error.ejs
  static/preloadRenderer.js
  static/preloads/api.js
  static/preloads/events.js
  static/preloads/handleErrors.js
  yarn.lock
Labels: PR: good to merge

#625 feat(menu): browser zoom
  src/main/index.js
  src/main/util/bindApplicationMenu.js
  src/main/util/bindMenus.js
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  static/preloadRenderer.js
  static/preloads/handleZoom.js
Labels: PR: good to merge

#637 feat(tx): priority fee notice
  src/renderer/account/components/TransactionsPanel/Send/PriorityFee/PriorityFee.js
  src/renderer/browser/components/RequestsProcessor/Invoke/index.js
  src/renderer/browser/components/RequestsProcessor/Send/index.js
  src/renderer/browser/hocs/withInvocationPrompt/index.js
  src/renderer/browser/hocs/withPrompt/index.js
  src/renderer/shared/components/Confirm/Confirm.js
  src/renderer/shared/components/Confirm/Confirm.scss
  src/renderer/shared/components/Modal/Modal.js
Labels: PR: good to merge

#652 feat(api): add version constant
  static/preloadRenderer.js
Labels: PR: needs review

#654 feat(settings): show current and latest versions
  src/renderer/settings/actions/versionActions.js
  src/renderer/settings/components/Settings/Settings.js
  src/renderer/settings/components/Settings/Settings.scss
  src/renderer/settings/components/Version/Version.js
  src/renderer/settings/components/Version/Version.scss
  src/renderer/settings/components/Version/index.js
  src/renderer/shared/components/Loading/Loading.js
Labels: PR: needs review

#659 chore(copy): fix copy to clipboard
  package.json
  yarn.lock
Labels: PR: needs review

#661 chore(copy): replace react-copy-to-clipboard with nos fork
  package.json
  src/renderer/account/components/TransactionsPanel/Receive/Receive.js
  src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.js
  yarn.lock
Labels: PR: good to merge

#662 chore(version): fix svg flicker on settings screen load
  src/renderer/settings/components/Version/Version.js
Labels: PR: good to merge

#666 chore(claim): fixed gas claim for ledger
  src/renderer/account/components/AccountPanel/ClaimButton/index.js
  src/renderer/browser/components/RequestsProcessor/ClaimGas/index.js
  src/renderer/browser/hocs/withSignTransactionToast.js
  src/renderer/shared/hocs/withProgressChange.js
  src/renderer/shared/util/claimGas.js
Labels: PR: good to merge

#674 chore(ux): restore mouse cursors throughout app
  src/common/stylesheets/mixins.scss
  src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.js
  src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.scss
  src/renderer/root/stylesheets/global.scss
  src/renderer/shared/components/Forms/Button/Button.scss
  src/renderer/shared/components/Forms/Select/Select.scss
  src/renderer/shared/components/Tabs/Tabs.scss
Labels: PR: needs review

#673 chore(claim): change button label while claiming
  src/renderer/account/components/AccountPanel/ClaimButton/ClaimButton.js
  src/renderer/account/components/AccountPanel/TokenBalance/index.js
Labels: PR: needs review

#672 feat(account): breakdown chart improvements
  src/renderer/account/components/AccountPanel/AccountPanel.scss
  src/renderer/account/components/AccountPanel/Breakdown/Breakdown.js
  src/renderer/account/components/AccountPanel/Breakdown/Breakdown.scss
  src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/BreakdownChart.js
  src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/BreakdownChart.scss
  src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/index.js
  src/renderer/account/components/AccountPanel/Breakdown/SectionLabel/SectionLabel.js
  src/renderer/account/components/AccountPanel/Breakdown/SectionLabel/SectionLabel.scss
  src/renderer/account/components/AccountPanel/Breakdown/TotalValue/TotalValue.js
  src/renderer/account/components/AccountPanel/Breakdown/TotalValue/TotalValue.scss
  src/renderer/account/components/AccountPanel/Breakdown/TotalValue/index.js
  src/renderer/account/components/AccountPanel/Breakdown/index.js
  src/renderer/account/util/calculateTokenValue.js
Labels: PR: needs review

#675 chore(account): prevent unnecessary scrolling
  src/renderer/account/components/Account/Account.js
  src/renderer/account/components/Account/Account.scss
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
Labels: PR: needs review

#676 chore(menu): fixed Inspect Element not displaying in prod
  src/renderer/browser/util/bindContextMenu.js
Labels: PR: needs review

#677 Update eslint-plugin-jest to the latest version 🚀
  package.json
  yarn.lock
Labels: greenkeeper

#516 chore(button): update styles
  src/renderer/shared/components/Forms/Button/Button.scss
  src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.scss
Labels: PR: needs review

#686 feat(rpc): filter nodes dynamically
  src/common/util/getRPCEndpoint.js
Labels: PR: needs review

#691 chore(rpc): select best height from good nodes
  src/common/util/getRPCEndpoint.js
Labels: PR: needs review

#693 chore(block): change polling frequency from 10 to 14 sec
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js
Labels: PR: needs review

#692 feat(balance): chunk nep5 balance calls
  src/renderer/shared/util/getBalances.js
  src/renderer/shared/util/getTokens.js
Labels: PR: needs review

#695 chore(balance): fix token icon centering
  src/renderer/account/components/AccountPanel/AccountPanel.scss
Labels: PR: needs review

#694 feat(balance): sort nos token first
  src/renderer/account/components/Account/index.js
  src/renderer/account/components/AccountPanel/Holdings/index.js
  src/renderer/shared/values/assets.js
Labels: PR: good to merge

#696 chore(account): localize token balances in holdings
  src/renderer/account/components/AccountPanel/TokenBalance/TokenBalance.js
Labels: PR: needs review

#699 feat(browser): multi testinvoke
  src/renderer/browser/actions/makeTestInvokeActions.js
  src/renderer/browser/components/RequestsProcessor/TestInvoke/index.js
  src/renderer/browser/util/createArrayScript.js
  src/renderer/browser/util/validateScriptArgs.js
Labels: PR: needs review
