Repository nos/client, pull requests merged in 2018-09, with the labels that each got.

#495 chore(package): revert redux upgrade
  package.json
  yarn.lock
Labels: PR: needs review

#470 feat(browser): added dynamic protocol handling
  __tests__/renderer/browser/util/parseURL.test.js
  src/renderer/browser/util/parseURL.js
  src/renderer/browser/values/protocols.js
Labels: PR: good to merge

#500 chore(browser): fix iframe navigate-in-page updating url
  src/renderer/browser/components/DAppContainer/DAppContainer.js
Labels: PR: good to merge

#499 feat(browser): perform search for non-URI queries
  __tests__/renderer/browser/util/parseURL.test.js
  package.json
  src/renderer/browser/util/parseURL.js
  yarn.lock
Labels: PR: needs review

#308 feat(browser): added attach assets to invocation
  __tests__/renderer/browser/components/RequestsProcessor/Send/index.test.js
  src/renderer/browser/actions/makeInvokeActions.js
  src/renderer/browser/components/RequestsProcessor/Invoke/index.js
  src/renderer/browser/hocs/withPrompt/index.js
  src/renderer/shared/util/formatAssets.js
  src/renderer/shared/util/getBalances.js
  src/renderer/shared/util/getTokens.js
  src/renderer/shared/util/sendAsset.js
  src/renderer/shared/values/assets.js
  static/preloadRenderer.js
Labels: PR: good to merge

#507 chore(login): select wallet file dialog context
  src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js
Labels: PR: needs review

#503 feat(select): advanced select component design
  __tests__/renderer/shared/components/Forms/Input/Input.test.js
  __tests__/renderer/shared/components/Forms/Select/Select.test.js
  __tests__/renderer/shared/components/Forms/Select/index.test.js
  package.json
  src/renderer/account/components/AccountPanel/TokenBalance/TokenBalance.js
  src/renderer/account/components/TokenIcon/TokenIcon.js
  src/renderer/account/components/TokenIcon/TokenIcon.scss
  src/renderer/account/components/TokenIcon/index.js
  src/renderer/account/components/TransactionsPanel/Send/Send.js
  src/renderer/account/components/TransactionsPanel/Send/TokenItem/TokenItem.js
  src/renderer/account/components/TransactionsPanel/Send/TokenItem/TokenItem.scss
  src/renderer/account/components/TransactionsPanel/Send/TokenItem/index.js
  src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js
  src/renderer/root/components/LoginLayout/LoginLayout.js
  src/renderer/root/components/LoginLayout/index.js
  src/renderer/settings/components/GeneralSettings/GeneralSettings.js
  src/renderer/settings/components/NetworkSettings/NetworkSettings.js
  src/renderer/settings/components/ScrollContainer/index.js
  src/renderer/settings/components/ScrollContainer/withScrollSpy.js
  src/renderer/settings/components/Settings/Settings.js
  src/renderer/shared/components/Dropdown/Dropdown.js
  src/renderer/shared/components/Dropdown/Dropdown.scss
  src/renderer/shared/components/Dropdown/index.js
  src/renderer/shared/components/Forms/Button/Button.js
  src/renderer/shared/components/Forms/Input/Input.js
  src/renderer/shared/components/Forms/Input/Input.scss
  src/renderer/shared/components/Forms/LabeledInput/LabeledInput.js
  src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.js
  src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.js
  src/renderer/shared/components/Forms/Select/DefaultItem/DefaultItem.js
  src/renderer/shared/components/Forms/Select/DefaultItem/DefaultItem.scss
  src/renderer/shared/components/Forms/Select/DefaultItem/index.js
  src/renderer/shared/components/Forms/Select/Select.js
  src/renderer/shared/components/Forms/Select/Select.scss
  src/renderer/shared/components/Modal/Modal.js
  src/renderer/shared/components/Modal/Modal.scss
  src/renderer/shared/components/Portal/Portal.js
  src/renderer/shared/components/Portal/Portal.scss
  src/renderer/shared/components/Portal/index.js
  src/renderer/shared/components/ScrollContainer/ScrollContainer.js
  src/renderer/shared/components/ScrollContainer/index.js
  src/renderer/shared/hocs/withScrollSpy.js
  src/renderer/shared/images/inputs/caret.svg
  src/renderer/shared/images/inputs/close.svg
  src/renderer/shared/images/inputs/search.svg
  src/renderer/shared/images/tokens/gas.svg
  src/renderer/shared/images/tokens/neo.svg
  src/renderer/shared/lib/scrollSpy.js
  src/renderer/shared/shapes/refShape.js
  src/renderer/shared/shapes/selectItemShape.js
  src/renderer/shared/util/anyPropsChanged.js
  yarn.lock
Labels: PR: good to merge

#515 chore(send): prevent reload
  src/main/index.js
Labels: PR: good to merge

#513 feat(invoke): invocation modal
  __tests__/renderer/browser/util/isValidAsset.test.js
  __tests__/renderer/browser/util/validateInvokeArgs.test.js
  __tests__/renderer/shared/components/TokenIcon/index.test.js
  __tests__/renderer/shared/util/hasDigits.test.js
  package.json
  src/common/stylesheets/variables.scss
  src/renderer/account/components/AccountPanel/TokenBalance/TokenBalance.js
  src/renderer/account/components/TransactionsPanel/Send/Send.js
  src/renderer/account/components/TransactionsPanel/Send/TokenItem/TokenItem.js
  src/renderer/browser/components/RequestsProcessor/Invoke/index.js
  src/renderer/browser/components/RequestsProcessor/Send/index.js
  src/renderer/browser/hocs/withInvocationPrompt/InvocationPrompt.js
  src/renderer/browser/hocs/withInvocationPrompt/index.js
  src/renderer/browser/hocs/withInvocationPrompt/styles.scss
  src/renderer/browser/hocs/withPrompt/index.js
  src/renderer/browser/hocs/withPrompt/styles.scss
  src/renderer/browser/hocs/withValidation.js
  src/renderer/browser/util/isValidAsset.js
  src/renderer/browser/util/validateInvokeArgs.js
  src/renderer/shared/components/Alert/Alert.js
  src/renderer/shared/components/Alert/Alert.scss
  src/renderer/shared/components/Confirm/Confirm.js
  src/renderer/shared/components/Confirm/Confirm.scss
  src/renderer/shared/components/Modal/Modal.scss
  src/renderer/shared/components/TokenIcon/TokenIcon.js
  src/renderer/shared/components/TokenIcon/TokenIcon.scss
  src/renderer/shared/components/TokenIcon/index.js
  src/renderer/shared/images/browser/invoke.svg
  src/renderer/shared/images/modal-gradient-vertical.png
  src/renderer/shared/images/modal-request-icon.png
  src/renderer/shared/shapes/assetsShape.js
  src/renderer/shared/util/formatAssets.js
  src/renderer/shared/util/getBalances.js
  src/renderer/shared/util/hasDigits.js
  yarn.lock
Labels: PR: good to merge

#519 chore(react): remove registerServiceWorker
  src/renderer/index.js
  src/renderer/registerServiceWorker.js
Labels: PR: needs review

#521 feat(block): poll for latest block
  .babelrc
  __tests__/fixtures/block.json
  __tests__/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.test.js
  __tests__/renderer/root/components/AuthenticatedLayout/StatusIcon/StatusIcon.test.js
  __tests__/renderer/shared/components/TokenIcon/index.test.js
  src/renderer/logout/components/Logout/index.js
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
  src/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.js
  src/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.scss
  src/renderer/root/components/AuthenticatedLayout/LastBlock/index.js
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss
  src/renderer/root/components/AuthenticatedLayout/StatusIcon/StatusIcon.js
  src/renderer/root/components/AuthenticatedLayout/StatusIcon/index.js
  src/renderer/root/components/AuthenticatedLayout/index.js
  src/renderer/shared/actions/blockActions.js
  src/renderer/shared/images/icons/statusConnected.svg
  src/renderer/shared/images/icons/statusDisconnected.svg
  src/renderer/shared/images/icons/statusUnknown.svg
  src/renderer/shared/shapes/blockShape.js
Labels: PR: needs review

#531 chore(block): fixed local block time
  src/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.js
Labels: PR: good to merge

#533 chore(nav): updated settings icon
  src/renderer/shared/images/icons/settings.svg
Labels: PR: good to merge

#523 chore(nav): add exchange sidebar link
  src/renderer/browser/values/browserValues.js
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js
  src/renderer/shared/images/icons/exchange.svg
Labels: PR: reviewed w/ comments

#530 feat(api): events api for blocks
  src/renderer/root/components/AuthenticatedLayout/index.js
  src/renderer/shared/hocs/withProgressChange.js
  src/renderer/shared/util/notifyWebviews.js
  static/preloadRenderer.js
Labels: PR: needs review

#532 feat(block): open block in neoscan tab
  src/renderer/root/components/AuthenticatedLayout/ExplorerLink/ExplorerLink.js
  src/renderer/root/components/AuthenticatedLayout/ExplorerLink/index.js
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js
  src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.js
Labels: PR: good to merge

#534 chore(tooltip): remove mouse leave delay
  src/renderer/shared/components/Tooltip/Tooltip.js
Labels: PR: needs review

#535 feat(balance): update balances on new blocks
  __tests__/renderer/root/components/Layout/AuthenticatedLayout/AuthenticatedLayout.test.js
  src/renderer/account/components/Account/index.js
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js
  src/renderer/root/components/AuthenticatedLayout/index.js
Labels: PR: good to merge, PR: reviewed w/ comments

#543 chore(network): resolve rpc endpoint from neoscan
  src/common/util/updateNetworks.js
  src/common/values/networks.js
  src/main/util/resolve.js
  src/renderer/root/components/App/index.js
  src/renderer/settings/actions/currentNetworkActions.js
  src/renderer/settings/components/NetworkSettings/NetworkSettings.js
Labels: PR: needs review

#538 feat(browser): add app menu and browser navigation controls
  __mocks__/electron.js
  __tests__/renderer/root/components/App/Routes.test.js
  package.json
  src/main/util/bindMenus.js
  src/renderer/browser/components/Browser/Browser.js
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  src/renderer/browser/components/DAppContainer/index.js
  src/renderer/browser/components/InternalPage/InternalPage.js
  src/renderer/browser/components/InternalPage/index.js
  src/renderer/browser/hocs/withWebviewIPC.js
  src/renderer/logout/components/Logout/index.js
  src/renderer/root/components/AuthenticatedLayout/AddressBar/index.js
  yarn.lock
Labels: PR: good to merge, PR: reviewed w/ comments

#550 chore(api): fixed ipc early unsubscribe
  static/preloadRenderer.js
Labels: PR: needs review

#549 chore(ci): fixed win32 deploy
  .circleci/config.yml
Labels: PR: needs review

#551 chore(menu): fixed reload button error for account/settings
  src/main/util/bindMenus.js
Labels: PR: good to merge

#562 feat(browser): fetch and render favicons
  __tests__/renderer/browser/actions/browserActions.test.js
  __tests__/renderer/browser/components/DAppContainer/DAppContainer.test.js
  __tests__/renderer/browser/index.test.js
  __tests__/renderer/browser/reducers/browserReducer.test.js
  __tests__/renderer/browser/util/fetchBestIcon.test.js
  __tests__/renderer/root/components/AuthenticatedLayout/Tab/index.test.js
  __tests__/setupFramework.js
  package.json
  src/renderer/browser/actions/browserActions.js
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  src/renderer/browser/components/DAppContainer/index.js
  src/renderer/browser/reducers/browserReducer.js
  src/renderer/browser/util/fetchBestIcon.js
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.js
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
  src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
  src/renderer/shared/images/browser/favicon.svg
  yarn.lock
Labels: PR: good to merge

#571 feat(forms): disabled input states
  src/renderer/shared/components/Forms/Input/Input.js
  src/renderer/shared/components/Forms/Input/Input.scss
  src/renderer/shared/components/Forms/Label/Label.js
  src/renderer/shared/components/Forms/Label/Label.scss
  src/renderer/shared/components/Forms/LabeledInput/LabeledInput.js
  src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.js
  src/renderer/shared/components/Forms/Select/Select.js
  src/renderer/shared/components/Forms/Select/Select.scss
Labels: PR: needs review

#578 chore(menu): fix reload accelerator
  src/main/util/bindMenus.js
Labels: PR: good to merge

#576 chore(favicon): use nos favicon for internal links
  src/renderer/root/components/AuthenticatedLayout/FavIcon/FavIcon.js
  src/renderer/root/components/AuthenticatedLayout/FavIcon/FavIcon.scss
  src/renderer/root/components/AuthenticatedLayout/FavIcon/index.js
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.js
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
  src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
  src/renderer/shared/images/browser/favicon-nos.svg
Labels: PR: needs review

#561 feat(ledger): sign invocations
  __tests__/renderer/browser/util/validateInvokeArgs.test.js
  __tests__/renderer/login/actions/authActions.test.js
  src/renderer/browser/actions/makeInvokeActions.js
  src/renderer/browser/components/RequestsProcessor/Invoke/index.js
  src/renderer/browser/components/RequestsProcessor/RequestProcessor.js
  src/renderer/browser/components/RequestsProcessor/mappings.js
  src/renderer/browser/hocs/withInvocationPrompt/index.js
  src/renderer/browser/hocs/withSignTransactionToast.js
  src/renderer/browser/util/validateInvokeArgs.js
  src/renderer/login/actions/authActions.js
  src/renderer/login/util/ledger.js
Labels: PR: needs review, PR: reviewed w/ comments

#588 chore(package:) updated version to 0.4.0
  package.json
Labels: PR: needs review

#590 chore(network): default to MainNet
  src/common/values/networks.js
Labels: PR: needs review

#600 Update recharts to the latest version 🚀
  package.json
  yarn.lock
Labels: greenkeeper

#595 feat(menu) open tab, open location, close tab, & shortcut keys
  __mocks__/electron.js
  src/main/util/bindMenus.js
  src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.js
  src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
  src/renderer/shared/components/Forms/Input/Input.js
Labels: PR: good to merge
