Repository nos/client, pull requests merged in 2018-05, with the labels that each got.

#119 feat(public):add support for splash screen on app load
  public/electron.js
  public/splash.html
Labels: community issue, enhancement, work-in-progress

#109 feat(settings): Add additional custom url network configurations
  src/actions/settings/currentNetworkActions.js
  src/actions/settings/networksActions.js
  src/components/App/index.js
  src/components/Settings/Settings.js
  src/components/Settings/Settings.scss
  src/components/Settings/index.js
  src/hocs/withAllNetworkData.js
  src/hocs/withNetworkData.js
  src/index.js
  src/util/initializeNetworks.js
  src/util/updateNetworks.js
  src/values/networks.js
Labels: community issue, enhancement, work-in-progress

#113 feat(Account): added ability to transfer funds on the account view
  package.json
  src/actions/dapps/makeSendActions.js
  src/actions/sendActions.js
  src/components/Account/Account.js
  src/components/Account/SendPanel/SendPanel.js
  src/components/Account/SendPanel/SendPanel.scss
  src/components/Account/SendPanel/index.js
  src/components/Forms/Select/Select.scss
  src/components/Icon/Icon.js
  src/components/Login/LoginFormWalletFile/LoginFormWalletFile.js
  src/hocs/withLoadingProp.js
  src/util/isNumeric.js
  src/util/sendAsset.js
  src/values/assets.js
  yarn.lock
Labels: enhancement, team issue

#122 chore(accessibility): add focus-ring management
  package.json
  src/components/AuthenticatedLayout/AddressBar/AddressBar.scss
  src/components/AuthenticatedLayout/ButtonBar/ButtonBar.scss
  src/components/AuthenticatedLayout/Navigation/Navigation.scss
  src/components/Forms/Button/Button.scss
  src/components/Forms/Input/Input.scss
  src/components/Forms/Select/Select.scss
  src/components/Settings/Settings.scss
  src/components/Tabs/Tabs.scss
  src/index.js
  src/stylesheets/global.scss
  yarn.lock
Labels: community issue, work-in-progress

#117 Added nos protocol & use it to resolve queries
  __tests__/components/App/Routes.test.js
  public/electron.js
  public/resolve.js
  src/actions/nameServiceActions.js
  src/actions/queryActions.js
  src/components/App/Routes/Routes.js
  src/components/AuthenticatedLayout/AddressBar/AddressBar.js
  src/components/AuthenticatedLayout/AddressBar/index.js
  src/components/AuthenticatedLayout/Breadcrumbs/BrowserBreadcrumb.js
  src/components/AuthenticatedLayout/Breadcrumbs/index.js
  src/components/AuthenticatedLayout/Navigation/Navigation.js
  src/components/Browser/Browser.js
  src/components/Browser/DAppContainer/DAppContainer.js
  src/components/Browser/DAppContainer/index.js
  src/components/Browser/index.js
  src/shapes/matchShape.js
  src/util/parseURL.js
Labels: enhancement, team issue, work-in-progress

#132 chore(api): return full result object instead of script
  src/browser/actions/makeTestInvokeActions.js
  src/browser/components/RequestsProcessor/TestInvoke/TestInvoke.js
  src/browser/components/RequestsProcessor/TestInvoke/index.js
  src/browser/shapes/resultStackShape.js
  src/browser/shapes/testInvokeShape.js
Labels: enhancement, team issue, work-in-progress

#135 chore(settings): refactorered settings design - structure
  src/account/components/SendPanel/SendPanel.js
  src/account/components/SendPanel/SendPanel.scss
  src/settings/components/NetworkPanel/NetworkPanel.js
  src/settings/components/NetworkPanel/NetworkPanel.scss
  src/settings/components/NetworkPanel/Saved/Saved.js
  src/settings/components/NetworkPanel/Saved/index.js
  src/settings/components/NetworkPanel/index.js
  src/settings/components/Saved/Saved.js
  src/settings/components/Saved/index.js
  src/settings/components/Settings/Settings.js
  src/settings/components/Settings/Settings.scss
  src/settings/components/Settings/index.js
  src/shared/components/Icon/index.js
Labels: enhancement

#127 feat(accounts): Login with saved encrypted account
  src/login/components/LoginFormWalletFile/LoginFormWalletFile.js
  src/login/components/LoginFormWalletFile/index.js
  src/register/components/AccountDetails/SaveAccount/SaveAccount.js
Labels: community issue, enhancement, work-in-progress

#136 feat(public): added icon
  package.json
  public/electron.js
  public/icons/icon1024x1024.icns
  public/icons/icon1024x1024.ico
  public/icons/icon1024x1024.png
Labels: enhancement, team issue, work-in-progress

#152 Chore/nos icon win
  package.json
  public/electron.js
  public/icons/icon1024x1024.ico
Labels: team issue, work-in-progress

#140 feat(splash): Updated splash screen
  .eslintignore
  public/animations/bodymovin_light_4_13.min.js
  public/animations/data.json
  public/animations/loader.js
  public/electron.js
  public/splash.html
Labels: PR: needs review

#153 chore(browser): refactored heirarchy and replaced actions/reducer
  __tests__/components/App/Routes.test.js
  package.json
  src/browser/actions/browserActions.js
  src/browser/actions/queryActions.js
  src/browser/components/AddressBar/AddressBar.js
  src/browser/components/AddressBar/AddressBar.scss
  src/browser/components/AddressBar/index.js
  src/browser/components/Browser/Browser.js
  src/browser/components/Browser/Browser.scss
  src/browser/components/Browser/index.js
  src/browser/components/ButtonBar/ButtonBar.js
  src/browser/components/ButtonBar/ButtonBar.scss
  src/browser/components/ButtonBar/index.js
  src/browser/components/DAppContainer/DAppContainer.js
  src/browser/components/DAppContainer/index.js
  src/browser/components/index.js
  src/browser/reducers/browserReducer.js
  src/browser/shapes/matchShape.js
  src/root/components/App/Routes/Routes.js
  src/root/components/AuthenticatedLayout/AddressBar/AddressBar.js
  src/root/components/AuthenticatedLayout/AddressBar/index.js
  src/root/components/AuthenticatedLayout/AuthenticatedLayout.js
  src/root/components/AuthenticatedLayout/Breadcrumbs/Breadcrumbs.js
  src/root/components/AuthenticatedLayout/Breadcrumbs/Breadcrumbs.scss
  src/root/components/AuthenticatedLayout/Breadcrumbs/BrowserBreadcrumb.js
  src/root/components/AuthenticatedLayout/Breadcrumbs/index.js
  src/root/reducers/index.js
  yarn.lock
Labels: PR: good to merge

#160 Added browser tabs
  .eslintrc.json
  __tests__/components/App/Routes.test.js
  public/welcome.html
  src/browser/actions/browserActions.js
  src/browser/components/AddressBar/index.js
  src/browser/components/Browser/Browser.js
  src/browser/components/Browser/Browser.scss
  src/browser/components/Browser/index.js
  src/browser/components/DAppContainer/DAppContainer.js
  src/browser/components/DAppContainer/index.js
  src/browser/components/Tab/Tab.js
  src/browser/components/Tab/Tab.scss
  src/browser/components/Tab/index.js
  src/browser/components/Tabs/Tabs.js
  src/browser/components/Tabs/Tabs.scss
  src/browser/components/Tabs/index.js
  src/browser/reducers/browserReducer.js
  src/browser/shapes/tabShape.js
  src/root/stylesheets/mixins.scss
  src/shared/components/Icon/Icon.js
Labels: PR: needs review

#159 feat(app): nOS API refactor
  README.md
  docs/api.md
  package.json
  src/browser/actions/makeInvokeActions.js
  src/browser/actions/makeStorageActions.js
  src/browser/actions/makeTestInvokeActions.js
  src/browser/components/RequestsProcessor/GetBalance/GetBalance.js
  src/browser/components/RequestsProcessor/GetBalance/index.js
  src/browser/components/RequestsProcessor/GetStorage/index.js
  src/browser/components/RequestsProcessor/Invoke/index.js
  src/browser/components/RequestsProcessor/Send/index.js
  src/browser/components/RequestsProcessor/TestInvoke/index.js
  src/browser/util/createScript.js
  src/browser/util/encodeArgs.js
  yarn.lock
Labels: PR: good to merge

#174 Fixed React prop warnings in tests
  __tests__/components/App/Routes.test.js
Labels: PR: good to merge

#172 chore(src): updated neonjs - fixed css issue
  src/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
  yarn.lock
Labels: PR: good to merge

#179 chore(browser): add closing tab functionality
  src/browser/components/DAppContainer/DAppContainer.js
  src/browser/components/DAppContainer/index.js
Labels: PR: reviewed w/ comments

#177 feat(browser): remove request queue when logout
  src/browser/actions/requestsActions.js
  src/browser/reducers/requestsReducer.js
  src/logout/components/Logout/index.js
Labels: PR: reviewed w/ comments

#181 chore(dev): change default port from 3000 to 4000
  package.json
Labels: PR: needs review

#178 Update getting started guide
  docs/create-your-own-dapp.md
Labels: PR: good to merge

#185 Cleaned up code from request queue changes
  .eslintrc.json
  public/electron.js
  src/browser/actions/makeBalancesAction.js
  src/browser/reducers/requestsReducer.js
  src/browser/util/createScript.js
  src/logout/components/Logout/index.js
Labels: PR: needs review

#183 Update yarn.lock to match dependencies
  yarn.lock
Labels: PR: needs review

#184 Change default port from 4000 to 5000
  package.json
  public/electron.js
  public/resolve.js
Labels: PR: good to merge

#173 chore(browser): add responsive tab
  src/browser/components/Tabs/Tabs.scss
Labels: PR: good to merge
