Repository nos/client, pull requests merged in 2018-08, with the labels that each got.

#395 chore(sidebar): fixed navigation icon stoke width
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss
Labels: PR: needs review

#399 chore(layout): fixed sizing for small windows
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
Labels: PR: needs review

#398 chore(balance): use rpc to get account state
  src/renderer/shared/util/getBalances.js
Labels: PR: good to merge

#401 chore(scss): added stylelint
  .stylelintrc
  package.json
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
  src/renderer/root/components/LoginLayout/LoginLayout.scss
  src/renderer/shared/components/Alert/Alert.scss
  src/renderer/shared/components/Confirm/Confirm.scss
  src/renderer/shared/components/Tabs/Tabs.scss
  yarn.lock
Labels: PR: good to merge

#402 chore(button): primary & secondary styles
  src/renderer/account/components/TransactionsPanel/Receive/Receive.js
  src/renderer/account/components/TransactionsPanel/Send/Send.js
  src/renderer/login/components/LoginFormLedger/LoginFormLedger.js
  src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.js
  src/renderer/login/components/LoginFormWIF/LoginFormWIF.js
  src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js
  src/renderer/register/components/AccountDetails/SaveAccount/SaveAccount.js
  src/renderer/register/components/RegisterForm/RegisterForm.js
  src/renderer/settings/components/NetworkSettings/NetworkSettings.js
  src/renderer/shared/components/Alert/Alert.js
  src/renderer/shared/components/Confirm/Confirm.js
  src/renderer/shared/components/Confirm/Confirm.scss
  src/renderer/shared/components/Forms/Button/Button.scss
  src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.js
  src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.scss
  src/renderer/shared/components/Forms/PrimaryButton/index.js
Labels: PR: good to merge

#414 feat(toasts): add success, error, and info toasts
  __tests__/renderer/register/components/RegisterForm/index.test.js
  __tests__/renderer/shared/actions/toastsActions.test.js
  __tests__/renderer/shared/reducers/toastsReducer.test.js
  src/common/stylesheets/mixins.scss
  src/renderer/login/hocs/withAuthError.js
  src/renderer/register/components/Register/Register.js
  src/renderer/register/components/Register/index.js
  src/renderer/register/components/RegisterForm/index.js
  src/renderer/root/components/App/App.js
  src/renderer/root/components/App/Toasts/Toast/Toast.js
  src/renderer/root/components/App/Toasts/Toast/Toast.scss
  src/renderer/root/components/App/Toasts/Toast/index.js
  src/renderer/root/components/App/Toasts/Toasts.js
  src/renderer/root/components/App/Toasts/Toasts.scss
  src/renderer/root/components/App/Toasts/index.js
  src/renderer/root/reducers/index.js
  src/renderer/settings/components/GeneralSettings/index.js
  src/renderer/settings/components/NetworkSettings/index.js
  src/renderer/shared/actions/toastsActions.js
  src/renderer/shared/hocs/withToast.js
  src/renderer/shared/images/toasts/success.svg
  src/renderer/shared/reducers/toastsReducer.js
  src/renderer/shared/shapes/toastShape.js
  src/renderer/shared/values/toasts.js
Labels: PR: good to merge

#417 chore(ui): native user interactions
  src/renderer/root/stylesheets/global.scss
  src/renderer/shared/components/Forms/Button/Button.scss
  src/renderer/shared/components/Tabs/Tabs.scss
Labels: PR: good to merge

#422 chore(register): fixed registration form
  src/renderer/register/components/RegisterForm/RegisterForm.js
  src/renderer/shared/components/Icon/Icon.js
  src/renderer/shared/components/Tabs/Tabs.js
Labels: PR: needs review

#428 chore(register): clean store between account creations
  __tests__/renderer/shared/hocs/withUnmountReset.test.js
  src/renderer/register/components/Register/index.js
  src/renderer/register/components/RegisterForm/index.js
  src/renderer/shared/hocs/withUnmountReset.js
Labels: PR: needs review

#431 chore(navigation): highlight active & focused links
  src/common/stylesheets/mixins.scss
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss
  src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.js
  src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.scss
  src/renderer/root/components/AuthenticatedLayout/TabLink/index.js
Labels: PR: good to merge, PR: reviewed w/ comments

#433 chore(tabs): replaced z-index with clip-path
  src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.scss
  src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
Labels: PR: needs review

#437 chore(deps): replaced react-router-redux w/ connected-react-router
  __tests__/renderer/shared/reducers/toastsReducer.test.js
  package.json
  src/renderer/root/components/Root/Root.js
  src/renderer/root/reducers/index.js
  src/renderer/root/store/configureStore.js
  src/renderer/shared/reducers/toastsReducer.js
  yarn.lock
Labels: PR: good to merge

#451 feat(settings): sidebar navigation
  .stylelintrc
  package.json
  src/renderer/settings/components/GeneralSettings/GeneralSettings.scss
  src/renderer/settings/components/SectionContent/SectionContent.scss
  src/renderer/settings/components/Settings/Settings.js
  src/renderer/settings/components/Settings/Settings.scss
  src/renderer/settings/components/SidebarLink/SidebarLink.js
  src/renderer/settings/components/SidebarLink/SidebarLink.scss
  src/renderer/settings/components/SidebarLink/index.js
  src/renderer/shared/components/Page/Page.js
  yarn.lock
Labels: PR: needs review

#455 chore(account): fixed TypeError for accounts with 3+ tokens
  config/webpack.renderer.js
  src/renderer/account/components/AccountPanel/Breakdown/Breakdown.js
Labels: PR: needs review

#452 chore(toast): copy to clipboard info toasts
  __tests__/renderer/register/components/AccountDetails/AccountDetails.test.js
  src/renderer/account/components/TransactionsPanel/Receive/Receive.js
  src/renderer/account/components/TransactionsPanel/Receive/index.js
  src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.js
  src/renderer/register/components/AccountDetails/AccountDatum/index.js
  src/renderer/root/components/App/Toasts/Toast/Toast.scss
Labels: PR: good to merge

#457 chore(webpack): fixed development build
  config/webpack.renderer.js
Labels: PR: needs review

#454 chore(style): treat tabbed content like web ux
  src/common/stylesheets/mixins.scss
  src/renderer/account/components/TransactionsPanel/Receive/Receive.scss
  src/renderer/account/components/TransactionsPanel/Send/Send.scss
  src/renderer/account/components/TransactionsPanel/TransactionsPanel.scss
  src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
  src/renderer/settings/components/NetworkSettings/NetworkSettings.scss
Labels: PR: needs review

#420 feat(circle): added build for win32
  .circleci/config.yml
Labels: PR: good to merge

#458 chore(nav): restore dapps link
  src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js
Labels: PR: good to merge

#461 chore(form): separate label into its own component
  __tests__/renderer/shared/components/Forms/Input/index.test.js
  __tests__/renderer/shared/components/Forms/Label/index.test.js
  __tests__/renderer/shared/components/Forms/LabeledInput/index.test.js
  __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js
  __tests__/renderer/shared/components/Forms/Select/index.test.js
  src/renderer/account/components/TransactionsPanel/Send/Send.js
  src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.js
  src/renderer/login/components/LoginFormWIF/LoginFormWIF.js
  src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js
  src/renderer/register/components/AccountDetails/SaveAccount/SaveAccount.js
  src/renderer/register/components/RegisterForm/RegisterForm.js
  src/renderer/settings/components/NetworkSettings/NetworkSettings.js
  src/renderer/shared/components/Forms/Input/Input.js
  src/renderer/shared/components/Forms/Input/Input.scss
  src/renderer/shared/components/Forms/Label/Label.js
  src/renderer/shared/components/Forms/Label/Label.scss
  src/renderer/shared/components/Forms/Label/index.js
  src/renderer/shared/components/Forms/LabeledInput/LabeledInput.js
  src/renderer/shared/components/Forms/LabeledInput/LabeledInput.scss
  src/renderer/shared/components/Forms/LabeledInput/index.js
  src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.js
  src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.scss
  src/renderer/shared/components/Forms/LabeledSelect/index.js
  src/renderer/shared/components/Forms/Select/Select.js
  src/renderer/shared/components/Forms/Select/Select.scss
Labels: PR: good to merge

#464 chore(settings): fixed settings select not showing label
  src/renderer/settings/components/GeneralSettings/GeneralSettings.js
  src/renderer/shared/components/Forms/Label/Label.js
Labels: PR: good to merge

#465 chore(deps): ignored electron-webpack
  package.json
Labels: PR: good to merge

#469 Greenkeeper/monorepo.enzyme 3.5.0
  __tests__/renderer/account/components/TransactionsPanel/index.test.js
  __tests__/renderer/account/index.test.js
  __tests__/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.test.js
  __tests__/renderer/register/components/AccountDetails/AccountDetails.test.js
  __tests__/renderer/shared/components/Forms/LabeledInput/index.test.js
  __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js
  package.json
  src/renderer/shared/components/Forms/Label/Label.js
  yarn.lock
Labels: greenkeeper

#412 chore(forms): forward component refs to DOM elements
  .codecov.yml
  README.md
  __tests__/renderer/shared/components/Forms/Input/Input.test.js
  __tests__/renderer/shared/components/Forms/Input/index.test.js
  __tests__/renderer/shared/components/Forms/LabeledInput/LabeledInput.test.js
  __tests__/renderer/shared/components/Forms/LabeledInput/index.test.js
  __tests__/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.test.js
  __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js
  __tests__/renderer/shared/components/Forms/Select/Select.test.js
  __tests__/renderer/shared/components/Forms/Select/index.test.js
  __tests__/setupFramework.js
  package.json
  src/renderer/shared/components/Forms/Button/Button.js
  src/renderer/shared/components/Forms/Button/index.js
  src/renderer/shared/components/Forms/Input/Input.js
  src/renderer/shared/components/Forms/Input/index.js
  src/renderer/shared/components/Forms/LabeledInput/LabeledInput.js
  src/renderer/shared/components/Forms/LabeledInput/index.js
  src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.js
  src/renderer/shared/components/Forms/LabeledSelect/index.js
  src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.js
  src/renderer/shared/components/Forms/PrimaryButton/index.js
  src/renderer/shared/components/Forms/Select/Select.js
  src/renderer/shared/components/Forms/Select/index.js
  src/renderer/shared/hocs/withForwardedRef.js
Labels: PR: needs review

#478 chore(tests): fixed missing prop warnings
  __tests__/renderer/shared/components/Forms/LabeledInput/index.test.js
  __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js
Labels: PR: good to merge

#479 feat(browser): fixed infinite loading spinner and title not updating
  __tests__/renderer/browser/actions/browserActions.test.js
  __tests__/renderer/browser/reducers/browserReducer.test.js
  src/renderer/browser/actions/browserActions.js
  src/renderer/browser/components/DAppContainer/DAppContainer.js
  src/renderer/browser/reducers/browserReducer.js
  src/renderer/root/components/AuthenticatedLayout/AddressBar/index.js
Labels: PR: good to merge

#490 chore(toasts): replaced modals with toasts, fixed network settings
  src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js
  src/renderer/login/components/LoginFormWalletFile/index.js
  src/renderer/root/components/App/Toasts/Toast/Toast.js
  src/renderer/settings/components/NetworkSettings/NetworkSettings.js
  src/renderer/settings/components/NetworkSettings/index.js
Labels: PR: good to merge

#493 Chore(deps): updated webpack/redux - removed redux from greenkeeper ignore
  package.json
  yarn.lock
Labels: PR: good to merge
